[package]
name = "rust-raymarcher"
version = "0.1.0"
authors = ["wegfawefgawefg <668es218pur@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
png = "0.16.8"